import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import TrpcClientProvider from "@/components/global/TrpcClientProvider";
import { MantineProvider } from '@mantine/core';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TrpcClientProvider><MantineProvider>{children}</MantineProvider></TrpcClientProvider>
      </body>
    </html>
  );
}
